name: Deploy ETicaretAPI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v6
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.0

